name: "Release"

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.2
      - name: node
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
      - name: Check if version has been updated
        uses: EndBug/version-check@v1
      - name: install npm dependencies
        if: steps.check.outputs.changed == 'true'
        run: npm install
      - name: build
        if: steps.check.outputs.changed == 'true'
        run: npm run rollup
      - name: publish
        if: steps.check.outputs.changed == 'true'
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}